articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # Create
    path('create/', views.create, name='create'), 
    # Read
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    # Update
    path('<int:id>/update/', views.update, name='update'),
    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Comment Create
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    # Comment Delete
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
]

modelForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) # 처음 게시물이 작성된 시간
    updated_at = models.DateTimeField(auto_now=True) # 수정된 시간, auto_now=True : 데이터가 저장되는 순간들을 계속해서 저장


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta():
        model = Article
        fields = '__all__'


class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('content', )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'index.html', context)

def create(request):
    # new/ => 빈 종이를 보여주는 기능
    # create/ => 사용자가 입력한 데이터 저장
    # -------------------------------------
    # GET create/ => 빈 종이를 보여주는 기능
    # POST create/ => 사용자가 입력한 데이터 저장
    # => create/로 합쳐짐

    if request.method == 'POST':
        form = ArticleForm(request.POST) # request.POST의 딕셔너리 값을 html으로 바꿔줌

        if form.is_valid(): # validation : form에 있는 데이터가 유효한가요?
            form.save() # 있다면 저장
            return redirect('articles:index')

    else: # 먼저 실행됨
        form = ArticleForm()

    # else일 경우 항상 실행
    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def detail(request, id):
    article = Article.objects.get(id=id)
    comments = article.comment_set.all()
    form = CommentForm()

    context = {
        'article': article,
        'form': form,
        'comments': comments,
    }
    return render(request, 'detail.html', context)


def update(request, id):
    article = Article.objects.get(id=id)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)
    
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }

    return render(request, 'update.html', context)


def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')


def comment_create(request, article_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

            article = Article.objects.get(id=article_id)
            comment.article = article
            comment.save()

            return redirect('articles:detail', id=article_id)

    else:
        return redirect('articles:index')


def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return redirect('articles:detail', id=article_id)

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
    <!--action=""을 비워두면 현재 위치로 다시 보냄(대신 GET에서 POST로 바뀜)
    => create함수의 if문으로 이동-->
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h3>{{article.title}}</h3>
    <p>{{article.content}}</p>
    <p>{{article.created_at}}</p>
    <p>{{article.updated_at}}</p>
    <a href="{% url 'articles:update' article.id %}">update</a>
    <a href="{% url 'articles:delete' article.id %}">delete</a>
    <a href="{% url 'articles:index' %}">articles</a>

    <hr>
    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

    <hr>
    {% for comment in comments %}
        <li>{{comment.content}}</li>
        <a href="{% url 'articles:comment_delete' article.id comment.id%}">delete</a>
    {% endfor %}
    {% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'articles:create' %}">new article</a>
    {% for article in articles %}
        <h3>{{article.title}}</h3>
        <p>{{article.content}}</p>
        <a href="{% url 'articles:detail' article.id %}">detail</a>
        <hr>
    {% endfor %}
{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>여기는 base</h1>
    {% block body %}

    {% endblock %}
</body>
</html>